theme: jekyll-theme-cayman
title: "gruppenkasse add-on"
plugins:
    - jekyll-polyglot
languages: ["en", "de"]
default_lang: "en"
exclude_from_localization: ["javascript", "images", "css"]
parallel_localization: true
exclude: [ "README.md", "Gemfile", "Gemfile.lock", "node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
